name: Compatibility tests

on:
  schedule:
    # at 5 am, every day
    - cron: 0 5 * * *
  workflow_dispatch:

jobs:
  get-hazelcast-versions:
      runs-on: ubuntu-slim
      outputs:
          versions: ${{ steps.versions.outputs.versions }}
      steps:
        - id: get-maintenance-versions
          uses: hazelcast/hazelcast/.github/actions/get-supported-maintenance-versions@master
        - id: versions
          run: |
              echo "versions=$(jq --compact-output 'map(. | tostring + ".0")' <<< '${{ steps.get-maintenance-versions.outputs.versions }}')" >> ${GITHUB_OUTPUT}

  build:
    runs-on: ubuntu-latest
    needs: get-hazelcast-versions
    permissions:
      contents: write
      actions: write
      checks: write
      pull-requests: write

    strategy:
      matrix:
        java: [ '17', '21', '25' ]
        hazelcast: ${{ fromJSON(needs.get-hazelcast-versions.outputs.versions) }}
        spring: [ { springSession: '3.5.6', springFramework: '6.2.18', springSecurity: '6.5.10' }, { springSession: '4.0.3', springFramework: '7.07', springSecurity: '7.0.5' } ]

    name: Build with Java ${{ matrix.java }} and Hazelcast ${{ matrix.hazelcast }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'gradle'

    - name: Build with Gradle
      run: |
        ./gradlew build -PhazelcastVersion="${{ matrix.hazelcast }}" \
          -PspringSessionVersion="${{ matrix.spring.springSession }}" \
          -PspringFrameworkVersion="${{ matrix.spring.springFramework }}" \
          -PspringSecurityVersion="${{ matrix.spring.springSecurity }}" 

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: test-results-java-${{ matrix.java }}-hz-${{matrix.hazelcast}}-springSession-${{matrix.spring.springSession}}
        path: |
          build/reports/tests/
          build/test-results/

    - name: Upload build artifacts
      if: success() && matrix.java == '17' && matrix.hazelcast == '5.6' && matrix.spring.springSession == '4.0.1'
      uses: actions/upload-artifact@v7
      with:
        name: build-artifacts
        path: build/libs/
