name: Compatibility tests

on:
  schedule:
    # at 5 am, every day
    - cron: 0 5 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '17', '21', '25' ]
        hazelcast: [ '5.4', '5.5', '5.6' ]
        spring: [ { springSession: '3.5.2', springFramework: '6.2.12', springSecurity: '6.5.5' }, { springSession: '4.0.0-M2', springFramework: '7.0.0-RC1', springSecurity: '7.0.0-M3' } ]

    name: Build with Java ${{ matrix.java }} and Hazelcast ${{ matrix.hazelcast }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'gradle'

    - name: Build with Gradle
      run: |
        ./gradlew build -PhazelcastVersion="${{ matrix.hazelcast }}" \
          -PspringSessionVersion="${{ matrix.spring.springSession }}" \
          -PspringFrameworkVersion="${{ matrix.spring.springFramework }}" \
          -PspringSecurityVersion="${{ matrix.spring.springSecurity }}" 

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-java-${{ matrix.java }}-hz-${{matrix.hazelcast}}-springSession-${{matrix.spring.springSession}}
        path: |
          build/reports/tests/
          build/test-results/

    - name: Upload build artifacts
      if: success() && matrix.java == '17' && matrix.hazelcast == '5.6' && matrix.spring.springSession == '4.0.0-M2'
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/libs/