name: OWASP CVE Checks

on:
  schedule:
    - cron: 0 2 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check dependencies

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'gradle'

    - name: Build with Gradle
      run: ./gradlew dependencyCheckAggregate --no-daemon

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: owasp-scan
        path: |
          build/reports/
